### ISSUE TITLE
iOS Arm64 Version does not Compile

### ISSUE THREAD

**Issue by jet082** [libretro/libretro-atari800#31]
It currently does not compile, but it can with the following changes.

Add this to the makefile

```
CFLAGS += -Wno-error=implicit-function-declaration
```

Comment out the following lines in ``atari800/src/devices.c``

```
                      if ((retval = system(command)) == -1)
                              Log_print("Print command \"%s\' failed", command);
#if defined(HAVE_UTIL_UNLINK) && !defined(VMS) && !defined(MACOSX)
                      if (Util_unlink(spool_file) != 0) {
                              perror(spool_file);
                      }
```

In ``atar800/src/monitor.c``

```
                        if (system(s + 1) == -1) {
                              printf("Error executing '%s'\n", s+1);
                        }
```

In ``atari/src/armeabi.c``

```
#if defined(__APPLE__) || HAVE_POSIX_MEMALIGN >= 1
   if (posix_memalign(&handle, 1024, size + 256) < 0)
      return 0;
#else
   handle = memalign(1024, size + 256);
#endif
```

In ``atari/src/aarch64.c``

```
#if HAVE_POSIX_MEMALIGN >= 1
   if (posix_memalign(&handle, 1024, size + 512) < 0)
      return 0;
#else
   handle = memalign(1024, size + 512);
#endif
```

**Comment by yoshisuga** [comment]
@jet082 Thanks for taking the time to find what the issue was. These issues can be resolved by using the appropriate preprocessor flags, as I did in #32 

`system()` calls are invalid on iOS and there's a flag for that - `HAVE_SYSTEM`, and we just needed the `HAVE_POSIX_MEMALIGN` flag enabled for iOS.

**Comment by jet082** [comment]
I can confirm that, now that the latest commits fixed the bug.
