### ISSUE TITLE
Not work on Wii

### ISSUE THREAD

**Issue by Edu789** [libretro/libretro-atari800#51]
Hello, I try to load atari 5200 using this core on Retroarch, but not any roms work, all bios files already put on system folder but still not work...

**Comment by twinaphex** [comment]
Does it still not work with the latest nightlies?

**Comment by Edu789** [comment]
It works, there are only those who change the color option for the 5200 system, otherwise the game does not start automatically.
seems to have a problem in the audio, but I believe it is normal for the Atari 5200 itself ...

**Comment by twinaphex** [comment]
OK, can you open up a separate Github issue for this? We can consider this one closed then.
