### ISSUE TITLE
Compiled on devkitpro for Wii but it's not working on nightlies, also controls not working.

### ISSUE THREAD

**Issue by metallic77** [libretro/libretro-atari800#55]
I compiled the atari800 core for Wii using devkitpro (r29-1) but same core is not working on nightlies, what i noticed is that when i cloned this source (using git clone command ) it didn't download all files (!) so that's why it wasn't compiling properly before. Manually downloaded the source, extracted to libretro-super, run the libretro-build-wii.sh script and bingo, it compiled and run on my Wii.

here is the .dol file.
https://www.dropbox.com/s/c84ldvchffvb2dw/atari800_libretro_wii.zip?dl=0

Also please look at fixing the controls for this core as the wiimote buttons are not working. Thanks

probably same issue with this
https://github.com/libretro/RetroArch/issues/11217

**Comment by trioan** [comment]
Safe to close ticket?

**Comment by metallic77** [comment]
Yes it is working now with controls etc.
