### ISSUE TITLE
Build error on Linux

### ISSUE THREAD

**Issue by Zombie-Ryushu** [libretro/libretro-atari800#62]
cc -c -olibretro/libretro-core.o libretro/libretro-core.c -O2 -mtune=atom -O2 -DNDEBUG -fPIC -D__LIBRETRO__  -DINLINE="inline" -DHAVE_CONFIG_H -Wall  -I. -I./atari800/src -I./libretro -I./libretro/libretro-common/include -I./libretro/libretro-common/include/compat/zlib  -I./deps/zlib
In file included from libretro/libretro-core.c:50:0:
libretro/cmdline.c: In function 'Add_Option':
libretro/cmdline.c:25:32: warning: embedded '\0' in format [-Wformat-contains-nul]
    sprintf(XARGV[PARAMCOUNT++],"%s\0",option);
                                ^
libretro/libretro-core.c: In function 'retro_init':
libretro/libretro-core.c:505:55: warning: embedded '\0' in format [-Wformat-contains-nul]
    if(retro_system_directory==NULL)sprintf(RETRO_DIR, "%s\0",".");
                                                       ^
libretro/libretro-core.c:506:28: warning: embedded '\0' in format [-Wformat-contains-nul]
    else sprintf(RETRO_DIR, "%s\0", retro_system_directory);
                            ^
libretro/libretro-core.c:508:41: warning: embedded '\0' in format [-Wformat-contains-nul]
    sprintf(retro_system_data_directory, "%s/data\0",RETRO_DIR);
                                         ^
libretro/libretro-core.c: In function 'retro_get_system_info':
libretro/libretro-core.c:598:37: error: expected ';' before 'GIT_VERSION'
    info->library_version  = "3.1.0" GIT_VERSION;
                                     ^
libretro/libretro-core.c: In function 'retro_run':
libretro/libretro-core.c:640:8: warning: unused variable 'x' [-Wunused-variable]
    int x;
        ^

**Comment by twinaphex** [comment]
Is this issue still ongoing?

**Comment by Zombie-Ryushu** [comment]
Yes it is.

**Comment by gouchi** [comment]
@Zombie-Ryushu On which  platform are your trying to compile it ?

Because compilation is fine one Linux x86_64.

Thank you.

**Comment by Zombie-Ryushu** [comment]
Linux x86_64. The error might be out of date,

**Comment by gouchi** [comment]
So please close this issue, if it is ok for you using latest commit.

Thank you.
