### ISSUE TITLE
Add RAM Size to core options

### ISSUE THREAD

**Issue by Darknior** [libretro/libretro-atari800#64]
Hi

We have on the CORE options the possibility to change : 

- Atari System
- Atari Standard
- Use Hi-Res or not

But we miss an important option for some games, 

- Change the RAM size

Please is it possible to add it to core options ?
It will help a lot to configure settings by games to make them working fine.

For the moment we must open the old menu

![Atari800-Configuration-Screen-Screenshot](https://user-images.githubusercontent.com/3703317/101394373-b5d23900-38c8-11eb-9010-2a96e95bea65.png)

- Open the Disk File
The the emulator write we have not enough RAM
- Open the old blue menu
- Go to the SYSTEM  SETTING
- Change the RAM Size
- And then .. launch the game

It's not really user friendly for the younger users.
Thanks a lot

**Comment by raphkoster** [comment]
I have played literally hundreds of games on this emulator and have never needed to adjust the RAM size independently of the machine. Can I ask what you are trying to launch that is causing this "not enough RAM" message?

The original Atari 8 bit machines only had fixed RAM sizes (this is from memory, so forgive me if I get these wrong):

400, 600XL: 16K
800: 48k
800XL, 1200XL: 64k
130XE: Two banks of 64k

For the vast majority of games, what matters is the machine type. Basically, there is no reason to ever try to emulate a 400 if you an do an 800, or a 600XL if you can do the 130XE.

There are a tiny amount of programs that call for the 130XE's two banks. And there may be a few demos from modern days that call for more, but they're definitely not "user friendly for younger users" sorts of things.

**Comment by Darknior** [comment]
Thanks for your answer.
I have work on A800 all the evening, i discover this old computer with pleasure ... 
I finally understand what you've do with machine type and ram size.
You configure the two at the same time. and it's not fine to only change the RAM size. 

But i have one game i know that ask for 320Kb of memory.
Now i can't remember how i do to launch it, but i'm sure it ask me 320 Kb of RAM

```
# Custom XL/XE (320 Mb) 
Atari XL/XE
RAM_SIZE=320 (RAMBO)
```

The game is  **Bomb Jack v1.5 (PL) (en) (FW)[320K].xex**

http://www.atarimania.com/game-atari-400-800-xl-xe-bomb-jack_21390.html

https://www.youtube.com/watch?v=eVBenUTZDeg

I don't know if some other homebrews ask also for more RAM like it

**Comment by raphkoster** [comment]
There are probably several more homebrews that call for more memory than the original machines shipped with, yes. RAM expansions to something like 320K like that game asks for were aftermarket solutions, basically customized machines.

The core leaves out a LOT of options from the emulator menu, and whoever first added core options definitely chose a very conservative approach to adding them, probably to keep the menu small and easy to use. I personally very much wish that the artifacting options were there, for example.

I periodically think about adding in the automatic file parsing I implemented here as a script: https://retropie.org.uk/forum/topic/22392/lr-atari800-5200-artifacting-basic-and-other-guidance

I would call this a valid bug, but probably lower priority than enabling a lot of the other options in the core, personally. But it's worth doing for completeness.

**Comment by Darknior** [comment]
You are right, it's not an important bug, and it's not really a bug.
I think it's easy only to add a new custom configuration that give us 320 Kb of RAM for modern homebrews.

Yes i've read your work and i love it.
For some one like me that discover this computer, it's magic :)

But same i discover you let us with ARTIFACTING yes / no 
But we can"t choose the palette 

```
ARTIFACT_NTSC_MODE=0  // off
ARTIFACT_NTSC_MODE=1  // blue/brown 1
ARTIFACT_NTSC_MODE=2  // blue/brown 2
ARTIFACT_NTSC_MODE=3  // GTIA
ARTIFACT_NTSC_MODE=4  // CTIA
```

Why letting us choose it in CORE options ? There are here for help users without python script. 
To configure games by games and save settings. Like we do on easy console settings.

**Comment by raphkoster** [comment]
The above settings are not something I wrote -- they were in the original emulator options. When the emulator was ported to Libretro, whoever did that exposed only "yes/no" in the core options -- probably because whoever ported it to Libretro didn't know how different the modes look.

The only work I have done for the actual core was fixing the keyboard and enabling the extra joystick ports on the 400/800.

The script I wrote was only designed to work for Retropie, but the thing I keep thinking about is instead adding that logic into the core itself, so that it can parse the filename and make the right choices. But that's off-topic for this bug report. :) Someday I will have free time to do it.

**Comment by Darknior** [comment]
Ok i understand better.

And yes some other core like THOMSON for MO5 TO8 use the same trick and read the game file name.
If it found some TAGs it will use them to configure the emulator.
For exemple to launch TO7 or MO5 automaticaly.

For sure you can use the same trick for ARTIFACT and maybe also the MEMORY. To auto adjust the ATARI to the game.

**Comment by grzybsonssg** [comment]
Hi!

Memory expansions are very popular among so-called demoscene, especially in Poland. As name suggests, this extra memory is used by demos. However straight out of head I can list a few games that require 320KB of RAM or more:
* International Karate Enhanced 2014 edition - single XEX file, additional options, locations,
* Commando - unreleased game, single XEX file
* Bomb Jack
* Pang
* Yie Ar Kung Fu
* Atari Blast (this requires 1088KB)
* In nihilum reverteris - text game with hires fonts and graphics

I sniffed a little in sources and found easy way to add new positions in "Atari System" option, pull request is awaiting :)

**Comment by Darknior** [comment]
Thanks a lot, i close the issue
